<a href="https://colab.research.google.com/github/bijoy-420/python-course-project/blob/main/Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Installing All Necessary Libraries

In [1]:
import numpy as np
import pandas as pd

# 1. Create a NumPy array with 20 random integers between 1 and 100 and its basic operations

In [7]:
random_array=np.random.randint(1,100,20)
print(f'\n Random Array')
print(random_array)
print(f'\n Mean of Random Array:',np.mean(random_array))
print(f'\n The sum of Random Array:',np.sum(random_array))
print(f'\n The standard deviation of Random Array:',np.std(random_array))
print(f'\n Max Number of random Array:',np.max(random_array))
print(f'\n Min Number of random Array:',np.min(random_array))

 Random Array
[12 78 65 29 24  5 67 81 61 84 73 37  3  7 46 10 57 79 85  6]

 Mean of Random Array: 45.45

 The sum of Random Array: 909

 The standard deviation of Random Array: 30.10892724757892

 Max Number of random Array: 85

 Min Number of random Array: 3

# 2. Creating a DataFrame with 5 rows and 3 columns of random numbers between 1 and 100 and its basic operations

In [10]:
random_number=np.random.randint(1,100,(5,3))
df=pd.DataFrame(random_number,columns=['A','B','C'])
print(f'\n DataFrame')
df

 DataFrame

    A   B   C
0  37  21  66
1  91  86  62
2  45  74  42
3  21  97  49
4  28  55  66

In [11]:
df.head()

    A   B   C
0  37  21  66
1  91  86  62
2  45  74  42
3  21  97  49
4  28  55  66

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [13]:
df.describe()

               A          B          C
count   5.000000   5.000000   5.000000
mean   44.400000  66.600000  57.000000
std    27.582603  29.871391  10.908712
min    21.000000  21.000000  42.000000
25%    28.000000  55.000000  49.000000
50%    37.000000  74.000000  62.000000
75%    45.000000  86.000000  66.000000
max    91.000000  97.000000  66.000000

In [17]:
df[['A','B']]

    A   B
0  37  21
1  91  86
2  45  74
3  21  97
4  28  55

In [20]:
df.iloc[3]

A    21
B    97
C    49
Name: 3, dtype: int64

In [21]:
df['D']=df['A']+df['B']
df

    A   B   C    D
0  37  21  66   58
1  91  86  62  177
2  45  74  42  119
3  21  97  49  118
4  28  55  66   83

In [22]:
df.isnull().sum()

A    0
B    0
C    0
D    0
dtype: int64